import styles from '../styles/pages/about-us.module.sass';
import { gsap } from 'gsap/dist/gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import { useEffect, useRef } from 'react';

gsap.registerPlugin(ScrollTrigger);

export default function () {
  useEffect(() => {
    gsap.utils.toArray('.slide-anime').forEach(slide => {
      gsap.fromTo(slide, {
        opacity: 0
      }, {
        scrollTrigger: {
          trigger: slide,
          scrub: 1,
          end: "center center",
          toggleActions: "restart pause reverse reset",
        },
        opacity: 1
      })
    })

    gsap.utils.toArray('.slide-anime:not(:last-child)').forEach((slide, i) => {
      gsap.fromTo(slide, {
        xPercent: i % 2 == 0 ? -50 : 50
      }, {
        scrollTrigger: {
          trigger: slide,
          scrub: 1,
          end: "center center",
          toggleActions: "restart pause reverse reset",
        },
        xPercent: 0
      })
    })
  }, [])

	return (

		<div className={styles.about}>
          <div>
      <h4>Introducing RECP, a sophisticated Real Estate Crypto Project bridging the gap between traditional real estate investment and blockchain technology. Our platform enables investors to acquire NFTs that represent tangible real estate assets, including residential properties, commercial buildings, and hotels. RECP provides a secure, user-friendly dApp for managing transactions while offering stability and security in the investment process.</h4>
    </div>
      <div className="slide-anime">
			  <img src="/img/about/temp.jpg" className={styles.img} />
        <div>
          <h2>About RECP</h2>
          <p>RECP is a trailblazing crypto project that seamlessly combines real estate investment opportunities with the benefits of blockchain technology. Our team of seasoned professionals in real estate, finance, and technology has developed a multi-blockchain, interoperable platform to facilitate secure and stable investments. RECP's foundation is built upon collaboration with real-life contractors, real estate project handlers, and a robust holding company, ensuring the reliability and stability of our platform and the investments it represents.</p>
        </div>
      </div>
      <div className="slide-anime">
			  <img src="/img/about/temp.jpg" className={styles.img} />
        <div>
          <h2>Our Mission</h2>
          <ul>
          <li><b>Explore investment opportunities:</b> Browse our carefully curated selection of residential properties, commercial buildings, and hotels.</li>
          <li><b>Acquire NFTs:</b> Purchase NFTs representing your chosen real estate assets and receive a share of the income generated by these properties.</li>
          <li><b>Generate revenue:</b> Your NFTs will produce income based on the performance of the underlying real estate investment.</li>
          <li><b>Trade on the marketplace:</b> Utilize our dApp to buy, sell, or auction your NFTs, as needed.</li>
          </ul>
        </div>
      </div>
      <div className="slide-anime">
			  <img src="/img/about/temp.jpg" className={styles.img} />
        <div>
          <h2>Features</h2>
          <ul>
          <li>Secure and user-friendly dApp for managing NFT transactions</li>
          <li>Multi-blockchain, interoperable platform</li>
          <li>Real estate investments supported by actual acquisitions, partnerships, and construction projects</li>
          <li>A diverse range of properties available for investment</li>
          <li>NFTs that generate revenue based on real estate income</li>
          <li>Stability and security for investors</li>
          </ul>
          </div>
      </div>
      <div className="slide-anime">
			  <img src="/img/about/temp.jpg" className={styles.img} />
        <div>
          <h2>Future Developments</h2>
          <p>RECP is dedicated to ongoing innovation and growth. We plan to incorporate cutting-edge technologies such as Augmented Reality (AR), Virtual Reality (VR), and 3D visualization powered by Unreal Engine to provide a more interactive and immersive experience for our users.</p>
        </div>
      </div>
      <div className="slide-anime">
			  <img src="/img/about/temp.jpg" className={styles.img} />
        <div>
          <h2>Partners</h2>
          <p>RECP collaborates with established real-life contractors and real estate project handlers to guarantee the quality, security, and stability of our investment offerings. Our strong network of industry professionals enables us to deliver unparalleled value to our investors.</p>
        </div>
      </div>
      <div className="slide-anime">
        <div style={{ maxWidth: '800px' }}>
          <h2>Why Choose RECP</h2>
          <h3>Integrity and Transparency</h3>
          <p>At RECP, we place a strong emphasis on integrity and transparency. Our platform is built upon real acquisitions, partnerships, and construction projects, setting us apart from other crypto projects in the market. We believe in providing our investors with a clear understanding of their investments and the underlying assets, instilling confidence in our approach.</p>
          <h3>Professional Network</h3>
          <p>Our collaboration with real-life contractors and real estate project handlers adds an extra layer of credibility and security to our investment offerings. Our network of industry professionals ensures that the properties on our platform are carefully vetted and managed, delivering exceptional value to our investors.</p>
          <h3>Continuous Improvement</h3>
          <p>RECP is dedicated to the ongoing improvement of our platform and the user experience. We understand the importance of staying ahead in the rapidly evolving real estate and blockchain industries. By incorporating advanced technologies such as AR, VR, and 3D visualization, we aim to create an immersive and interactive experience for our users, setting new standards in the NFT real estate space.</p>
          </div>
      </div>
		</div>
	)
}